### ISSUE TITLE
Getting null value for the previous page in the last page

### ISSUE THREAD

**Issue by brainykarthi** [uxman-sherwani/rails_api_paginate#1]
Getting null value for the previous page in the last page https://monosnap.com/file/v4uX2dKDKaeH8K0eyfCEaNlD9ycCDG

**My suggestion**
lib/rails_api_paginate.rb line 25
From
prev_page = current_page - 1 if current_page > 1 && current_page < total_pages
To
prev_page = current_page - 1 if current_page > 1 && current_page <= total_pages

Thanks in Advance

**Comment by uxxman** [comment]
Hi @brainykarthi if you want you can submit a PR and I will merge it :)

**Comment by uxxman** [comment]
fixed in #2
